platform :ios, '11.0'

target 'DMSGoPGP-Example' do
  use_frameworks!
  pod 'DMSGoPGP', :path => '../', :testspecs => ['Tests']

  target 'DMSGoPGP-ExampleTests' do
    inherit! :search_paths

  end

end
